backend:
  name: git-gateway

locale: "nl"
media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "piece" # Used in routes, ie.: /admin/collections/:slug/edit
    identifier_field: title
    slug: "{{number}}-{{title}}"
    label: "Stuk" # Used in the UI, ie.: "New Post"
    folder: "site/content/piece" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Route", name: route, widget: string}
      - {label: "Museumnummber", name: number, widget: string}
      - {label: "Admin.naam", name: title, widget: string}
      - label: "Afbeeldingen"
        label_singular: "Afbeelding"
        name: images
        widget: list
        required: false
        min: 0
        field: {label: "Afbeelding", name: file, widget: image, allow_multiple: false}
      - label: "Geluidsfragmenten"
        label_singular: "Geluidsfragment"
        name: sounds
        widget: list
        required: false
        min: 0
        field: {label: "Geluidsfragment", name: file, widget: file, allow_multiple: false}
      - label: "Nederlands"
        name: nl
        widget: object
        fields:
          - {label: "Naam", name: name, widget: string}
          - {label: "Korte tekst", name: short, widget: markdown, minimal: true, modes: [rich_text]}
          - {label: "Lange tekst", name: long, widget: markdown, minimal: true, modes: [rich_text]}
      - label: "Engels"
        name: en
        widget: object
        collapsed: true
        fields:
          - {label: "Naam", name: name, widget: string, required: false}
          - {label: "Korte tekst", name: short, widget: markdown, minimal: true, modes: [rich_text], required: false}
          - {label: "Lange tekst", name: long, widget: markdown, minimal: true, modes: [rich_text], required: false}
      - label: "Duits"
        name: de
        widget: object
        collapsed: true
        fields:
          - {label: "Naam", name: name, widget: string, required: false}
          - {label: "Korte tekst", name: short, widget: markdown, minimal: true, modes: [rich_text], required: false}
          - {label: "Lange tekst", name: long, widget: markdown, minimal: true, modes: [rich_text], required: false}
  - name: "page"
    label: "Losse pagina's"
    folder: "site/content/page"
    create: true
    fields:
      - {label: "Title", name: title, widget: string}
      - {label: "Subtitle", name: subtitle, widget: string}
      - {label: "Body", name: body, widget: markdown, minimal: true, modes: [rich_text]}
  - name: "pages"
    label: "Vaste pagina's"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: markdown, minimal: true, modes: [rich_text]}]}
          - {label: "Stukken intro", name: pieces_intro, widget: markdown, minimal: true, modes: [rich_text]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: number}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
